const test=require('node:test');const assert=require('node:assert/strict');const {World,AI,Keyboard,MAPS,motion}=require('../src/combat.js');
function ticks(w,n,cmd=[{},{}]){for(let i=0;i<n;i++)w.step(cmd);}
test('startup does not cause instant damage; active frame hits once',()=>{const w=new World();w.fighters[0].x=510;w.fighters[1].x=640;w.step([{action:'heavy'},{}]);assert.equal(w.fighters[1].hp,100);ticks(w,9);assert.equal(w.fighters[1].hp,100);ticks(w,10);assert.equal(w.fighters[1].hp,89);});
test('cooldown, cost and recovery are enforced',()=>{const w=new World(),f=w.fighters[0];f.energy=20;assert.equal(w.start(f,'ultimate'),false);f.energy=100;assert.equal(w.start(f,'cross'),true);assert.equal(f.energy,76);assert.equal(w.start(f,'cross'),false);ticks(w,60);assert.equal(w.start(f,'cross'),false);});
test('guard reduces damage; throw bypasses guard',()=>{const w=new World(),a=w.fighters[0],b=w.fighters[1];a.x=500;b.x=619;b.guard=true;w.hit(a,b,require('../src/combat.js').MOVES.heavy,'1');assert.equal(b.hp,98);b.invul=0;b.guard=true;w.hit(a,b,require('../src/combat.js').MOVES.death,'2');assert.equal(b.hp,83);});
test('three-key chord has priority over two-key throw',()=>{const k=new Keyboard(MAPS[0]);k.key('KeyJ',true);k.sample(0,1);k.key('KeyK',true);k.sample(1,1);k.key('KeyL',true);k.sample(2,1);assert.equal(k.sample(4,1).action,'ultimate');});
test('held attack is not retriggered; release clears key',()=>{const k=new Keyboard(MAPS[0]);k.key('KeyJ',true);k.sample(0,1);assert.equal(k.sample(4,1).action,'light');assert.equal(k.sample(5,1).action,null);k.key('KeyJ',false);assert.equal(k.held.size,0);});
test('relative motions reverse with facing',()=>{for(const face of [1,-1]){const k=new Keyboard(MAPS[0]);k.key('KeyS',true);k.sample(0,face);k.key('KeyS',false);k.key(face===1?'KeyD':'KeyA',true);k.sample(5,face);k.key('KeyK',true);k.sample(6,face);assert.equal(k.sample(10,face).action,'flame');}});
test('numpad and number row are independent',()=>{const k=new Keyboard(MAPS[1]);assert.equal(k.key('Digit1',true),false);assert.equal(k.key('Numpad1',true),true);k.sample(0,-1);assert.equal(k.sample(4,-1).action,'light');});
test('expired directional input cannot produce special',()=>{assert.equal(motion([{dir:'d',frame:0},{dir:'f',frame:3}],'j',50),'light');});
test('blink changes side; shield activates only after startup',()=>{const w=new World(),f=w.fighters[0];w.start(f,'blink');ticks(w,7);assert.ok(f.x>w.fighters[1].x);const a=new World();a.start(a.fighters[0],'rock');ticks(a,8);assert.equal(a.fighters[0].shield,0);ticks(a,1);assert.equal(a.fighters[0].shield,100);});
test('deterministic AI match finishes with finite, bounded state',()=>{function run(){const w=new World(12345),ais=[new AI(0),new AI(1)];for(let i=0;i<9000&&!w.over;i++)w.step(ais.map(a=>a.sample(w)));assert.ok(w.over);for(const f of w.fighters){assert.ok(f.hp>=0&&f.hp<=100);assert.ok(f.energy>=0&&f.energy<=100);assert.ok(f.x>=70&&f.x<=1210);}return [w.frame,w.winner,...w.fighters.map(f=>f.hp)];}assert.deepEqual(run(),run());});
