const test=require('node:test');
const assert=require('node:assert/strict');
const {World,AI,Keyboard,MAPS,MOVES,motion,MAX_RAGE}=require('../src/combat.js');
function ticks(w,n,cmd=[{},{}]){for(let i=0;i<n;i++)w.step(cmd);}
function pair(){const w=new World();w.fighters[0].x=490;w.fighters[1].x=625;return w;}
function until(w,predicate,max=1000){for(let i=0;i<max;i++){if(predicate())return;w.step();}throw Error('Condition not reached');}
test('startup delays damage and one hit is not repeated',()=>{const w=pair();w.step([{action:'heavy'},{}]);ticks(w,9);assert.equal(w.fighters[1].hp,100);ticks(w,20);assert.equal(w.fighters[1].hp,89);});
test('energy, cooldown and whiff recovery apply to all controllers',()=>{const w=pair(),f=w.fighters[0];f.energy=20;assert.equal(w.start(f,'cross'),false);f.energy=100;assert.ok(w.start(f,'cross'));assert.equal(f.energy,76);assert.equal(w.start(f,'cross'),false);ticks(w,70);assert.equal(w.start(f,'cross'),false);});
test('rage is distinct from energy and does not regenerate passively',()=>{const w=new World(),f=w.fighters[0];f.energy=100;assert.equal(w.start(f,'ultimate'),false);ticks(w,200);assert.equal(f.rage,0);f.rage=MAX_RAGE;f.energy=0;assert.ok(w.start(f,'ultimate'));assert.equal(f.rage,0);assert.equal(f.energy,0);});
test('super cut-in freezes simulation timer and move age',()=>{const w=pair(),f=w.fighters[0];f.rage=300;w.start(f,'ultimate');const time=w.time;const frame=w.frame;ticks(w,38);assert.equal(w.time,time);assert.equal(w.frame,frame);assert.equal(f.move.age,0);w.step();assert.equal(w.time,time-1);});
test('ordinary hit grants rage to both fighters',()=>{const w=pair(),[a,b]=w.fighters;w.hit(a,b,MOVES.light,'x');assert.ok(a.rage>0);assert.ok(b.rage>0);assert.equal(a.combo,1);});
test('super cannot refund its own rage',()=>{const w=pair(),[a,b]=w.fighters;a.rage=0;w.hit(a,b,MOVES.ultimate,'x');assert.equal(a.rage,0);assert.ok(b.rage>0);});
test('confirmed light-light-heavy chain reaches three real hits',()=>{const w=pair(),[a,b]=w.fighters;w.start(a,'light');until(w,()=>a.move?.confirmed);assert.ok(w.start(a,'light'));assert.equal(a.move.def.id,'light2');until(w,()=>a.move?.confirmed);assert.ok(w.start(a,'heavy'));until(w,()=>a.combo>=3);assert.equal(a.combo,3);assert.ok(b.hp<85);assert.ok(b.vh>0);});
test('whiff cannot be canceled into the second light',()=>{const w=new World(),a=w.fighters[0];w.start(a,'light');ticks(w,8);assert.equal(w.start(a,'light'),false);assert.equal(w.start(a,'heavy'),false);});
test('blocked attack cannot use on-hit cancels',()=>{const w=pair(),[a,b]=w.fighters;b.shield=200;w.start(a,'light');until(w,()=>b.hp<100);assert.equal(a.move.confirmed,false);assert.equal(w.start(a,'heavy'),false);});
test('hit-stop preserves buffered attack edge',()=>{const w=pair(),a=w.fighters[0];w.start(a,'light');until(w,()=>a.move?.confirmed);assert.ok(w.freeze>0);w.step([{action:'light'},{}]);until(w,()=>a.move?.def.id==='light2');assert.equal(a.move.def.id,'light2');});
test('combo damage scales down and resets after hitstun ends',()=>{const w=pair(),[a,b]=w.fighters;w.hit(a,b,MOVES.heavy,'1');const first=100-b.hp;w.hit(a,b,MOVES.heavy,'2');const second=100-first-b.hp;assert.ok(second<first);ticks(w,100);assert.equal(a.comboActive,false);w.hit(a,b,MOVES.light,'3');assert.equal(a.combo,1);});
test('holding guard reduces damage; throw bypasses it',()=>{const w=pair(),[a,b]=w.fighters;b.guard=true;w.hit(a,b,MOVES.heavy,'1');assert.equal(b.hp,98);b.invul=0;b.guard=true;w.hit(a,b,MOVES.death,'2');assert.equal(b.hp,83);});
test('fresh guard parries without chip damage',()=>{const w=pair(),[a,b]=w.fighters;b.guard=true;b.guardAt=w.frame;w.hit(a,b,MOVES.heavy,'x');assert.equal(b.hp,100);assert.equal(w.events.at(-1).parry,true);assert.equal(b.rage,16);});
test('guard break causes full damage and punishable stun',()=>{const w=pair(),[a,b]=w.fighters;b.guard=true;b.guardMeter=1;w.hit(a,b,MOVES.heavy,'x');assert.equal(b.hp,89);assert.equal(b.stun,42);assert.equal(w.events.at(-1).broken,true);});
test('same-frame normal attacks trade rather than favoring P1',()=>{const w=pair();w.start(w.fighters[0],'light');w.start(w.fighters[1],'light');ticks(w,6);assert.equal(w.fighters[0].hp,94);assert.equal(w.fighters[1].hp,94);});
test('three-key chord outranks two-key throw',()=>{const k=new Keyboard(MAPS[0]);k.key('KeyJ',true);k.sample(0,1);k.key('KeyK',true);k.sample(1,1);k.key('KeyL',true);k.sample(2,1);assert.equal(k.sample(4,1).action,'ultimate');});
test('four simultaneous keys do not cast a super',()=>{const k=new Keyboard(MAPS[0]);for(const code of ['KeyJ','KeyK','KeyL','KeyS'])k.key(code,true);k.sample(0,1);assert.equal(k.sample(4,1).action,null);});
test('held key has no auto-repeat',()=>{const k=new Keyboard(MAPS[0]);k.key('KeyJ',true);k.sample(0,1);assert.equal(k.sample(4,1).action,'light');k.key('KeyJ',true);assert.equal(k.sample(8,1).action,null);k.key('KeyJ',false);assert.equal(k.held.size,0);});
test('physical keypad differs from the number row',()=>{const k=new Keyboard(MAPS[1]);assert.equal(k.key('Digit1',true),false);assert.ok(k.key('Numpad1',true));k.sample(0,-1);assert.equal(k.sample(4,-1).action,'light');});
test('directional motions reverse with fighter facing',()=>{for(const face of [1,-1]){const k=new Keyboard(MAPS[0]);k.key('KeyS',true);k.sample(0,face);k.key('KeyS',false);k.key(face===1?'KeyD':'KeyA',true);k.sample(5,face);k.key('KeyK',true);k.sample(6,face);assert.equal(k.sample(10,face).action,'flame');}});
test('old directional input expires',()=>{assert.equal(motion([{dir:'d',frame:0},{dir:'f',frame:3}],'j',50),'light');});
test('clear removes held keys and pending chord',()=>{const k=new Keyboard(MAPS[0]);k.key('KeyJ',true);k.sample(0,1);k.clear();assert.equal(k.held.size,0);assert.equal(k.sample(10,1).action,null);});
test('down + guard accepts either key order',()=>{for(const codes of [['KeyS','KeyL'],['KeyL','KeyS']]){const k=new Keyboard(MAPS[0]);k.key(codes[0],true);k.sample(0,1);k.key(codes[1],true);assert.equal(k.sample(1,1).action,'rock');}});
test('shield and blink occur at active frame only',()=>{const w=new World(),f=w.fighters[0];w.start(f,'blink');ticks(w,7);assert.ok(f.x>w.fighters[1].x);const a=new World();a.start(a.fighters[0],'rock');ticks(a,8);assert.equal(a.fighters[0].shield,0);ticks(a,1);assert.equal(a.fighters[0].shield,100);});
test('rage never exceeds three stocks',()=>{const w=pair(),[a,b]=w.fighters;for(let i=0;i<100;i++){b.hp=100;w.hit(a,b,MOVES.light,''+i);}assert.equal(a.rage,300);assert.equal(b.rage,300);});
test('same seeded AI match is deterministic and finishes',()=>{function run(){const w=new World(12345),ais=[new AI(0),new AI(1)];for(let i=0;i<14000&&!w.over;i++)w.step(ais.map(a=>a.sample(w)));assert.ok(w.over);for(const f of w.fighters){assert.ok(f.hp>=0&&f.hp<=100);assert.ok(f.energy>=0&&f.energy<=100);assert.ok(f.rage>=0&&f.rage<=300);assert.ok(f.x>=70&&f.x<=1210);}return [w.frame,w.winner,...w.fighters.map(f=>f.hp)];}assert.deepEqual(run(),run());});
